# Use an official image of Node.js runtime
FROM node:22-alpine

#Set the Working directory inside the container
WORKDIR /app


#Copy all the package.json files in the working directory
COPY package*json ./

#Install dependencies
RUN npm install

COPY . .

ENV PORT=3000

CMD ["node","index.js"]